name: Test experiment_metadata tasks

on: [pull_request]

jobs:
  setup:
    name: ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Add workspace to path
        run: |
          echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH

      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 1
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{hashFiles('test-environment.yml') }}
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: test-environment.yml
          mamba-version: "*"
          python-version: 3.6
          channels: ebi-gene-expression-group,conda-forge,bioconda,defaults
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true
      
      - name: Run tests
        run: |
          atlas-experiment-metadata-test.bats

      #- name: Linting
      #  uses: snakemake/snakemake-github-action@v1
      #  with:
      #    directory: 'test_data'
      #    snakefile: 'zooma-mappings-wf/Snakefile'
      #    args: '--lint --config mode="atlas" working_dir=../test_data debugging=true zooma_logs=../test_data zooma_exclusions=../test_data/zooma_exclusions.yml load_zooma_jobs=30 prot_magetabfiles=/magetab_path/ temp_dir=../test_data zoomaMetadataUrl=zoomaMetadataUrl notifEmail=false retryWithoutZooma=no experiment_metadata_dir=experiment_metadata_dir atlas_prod_co=atlas_prod_co lsf_config=lsf_config previousRunDate=previous_run dest=dest keep_backup_sdrf=false'

